apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-istio-ingress-to-backend
  namespace: {{ .Values.backend.namespace }}
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: {{ .Values.gateway.namespace }}
  to:
    - group: ""
      kind: Service
      name: {{ .Values.backend.name }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-istio-ingress-to-frontend
  namespace: {{ .Values.frontend.namespace }}
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: {{ .Values.gateway.namespace }}
  to:
    - group: ""
      kind: Service
      name: {{ .Values.frontend.name }}
