host: deploy.arguswatcher.net

gateway:
  namespace: istio-ingress
  # Existing istio-ingressgateway Service that the Gateway API Gateway binds to
  serviceName: istio-gateway

backend:
  name: backend
  namespace: backend
  port: 80

frontend:
  name: frontend
  namespace: frontend
  port: 80

tls:
  enabled: true
  httpsRedirect: false
  secretName: deploy-tls
  issuer:
    email: simonangelfong@gmail.com
    # server: https://acme-v02.api.letsencrypt.org/directory   # prod
    server: https://acme-staging-v02.api.letsencrypt.org/directory
