apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-03-frontend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/simonangel-fong/argocd-argorollout-istio
    targetRevision: master
    path: app/frontend
    helm:
      releaseName: frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
